version: "3.8"

services:
  mongo:
    image: mongo
    container_name: cruds_track4go_db
    expose:
      - 27017

  express:
    container_name: cruds_track4go_api
    image: cruds_track4go_api
    ports:
      - 3000:3000
    build:
      context: ./back_end

  react:
    container_name: cruds_track4go_react
    image: cruds_track4go_react
    ports:
      - 80:80
    build:
      context: ./front_end