name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Login to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSOWRD
      - 
        name: Build backend
        run: |
          docker build ./back_end -t josluna98/express_api:exercise
      - 
        name: Build frontend
        run: |
          docker build ./front_end -t josluna98/react_ui:exercise
      - name: Docker push
        run: |
          docker push josluna98/express_api:exercise
          docker push josluna98/react_ui:exercise
